### PR TITLE
Menu item listing

### LINKED ISSUE #6: List restaurants' menu items
As a client, I want to be able to see all the menu items for any restaurant so I can understand what each restaurant provides for me.

### Tasks:
* Create a separate `.ui` file
* Display the menu items given a restaurant

### Tests:
* Display a restaurant with `0` menu items
* Display a restaurant with `1` menu items
* Display a restaurant with `5` menu items

### Definition of done:
* When a restaurant is selected and the menu button is pressed the user will be able to see the menu items of that restaurant

**Priority:** Highest

### PR DESCRIPTION
**Pull request by ChrisRzech**
Closes #6 

### Key features
* Able to list all menu items of a given restaurant
* If needed, the list is able to display a quantity spin box that will record all changes
* When needed, the list is able to return an `std::map` of all the menu IDs and quantity related to it
* `View Restaurants` now displays all menu items when a restaurant is selected

### Future Improvements
* none

### Notes
When `MenuItem` holds a menu item ID (backend future update), make sure to set the `m_id` in `MenuListItem` appropriately.

### CODE REVIEW

**Comment by Roger-Chavez** [comment]
Any chance we can get a header that displayers the restaurant name on top of menu list and text below that that says menu items?

**Review by Roger-Chavez — APPROVED** [review]
Looks good

**Comment by typokign** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

latest commit is signed by untrusted key plz fix
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEiJJ0EZtGdMJUlGXNQ31u2GPIkbAFAlyUet8ACgkQQ31u2GPI
kbBjzBAApPj1AtdbBhblXXBeRRNYpj6wbt91Hf2jnKE9XyltLNBliEyUnyEbmfsC
EJfD3W7sc/tPpmNiirIZ/5u43hNcRLvWaD72F6USdiaw9PsktrNTnjvckPSZx4BN
jN0/6SuzchB+bSAfG7UiKc2Vxks4a5UJffttjBBulAQklx2/TK3F87lO3Prcvit4
79g92SryQxxOoifnaMAi2e7J57CpP3UZaKQ9O+pQHMlDqr+0yF2mvPzGHbRHZxJa
jFLPGceOnR9Hj+ulAIWTA2wG/YkZXaF7D4ISaPbG7Yq+Dov2EEAFrpV6LQuW+UWE
PN593HDCgZvu9w4B4aP5zR+uAZ+alxAnZAz3sApqn+/sDCvgscGW0V3DvSggklg4
ddAZqUmOaleKpRhlaVYVn9Qud+ow8YKY7scM9ikXjzflrrndaCy/mv6kM04GFPtw
G1KmGPQFkY6wgS+pqSkOo/OUb88PyY2LfnqS5KNmj7a0XHa8BoavyYwMmHgqEdq8
ylAVRxaKTxtqdbLER0EQZaYAZ7AphUgV0/AMkDEk3hbGIl/FVNvYiXAFzADW2/Ml
lEXu0UXVHBkPOmLvhAl4KjALGhg5NcC/mHyDIbRwb1Ka7fb2CcGWtrnkKCK4fksa
27tiq4gcertjdLk/zY1pcDMlh1QlQS3SHMjQbs/5Ux1HiawmCEY=
=3qwR
-----END PGP SIGNATURE-----
```

**Review by Roger-Chavez — APPROVED** [review]
Compiles and runs on my computer

**Pull request merged**
